// DbTempProdutos.js
// Simulação de tabela PRODUTO com 10 produtos fictícios

const produtos = [
  {
    id: 1,
    qtd: 3,
    nome: "Paracetamol 500mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "MedPharma",
    dataValidade: "2026-01-01",
    preco: 12.5,
    existe: true,
  },
  {
    id: 2,
    qtd: 3,
    nome: "Ibuprofeno 400mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "SaúdeMais",
    dataValidade: "2025-12-01",
    preco: 18.9,
    existe: true,
  },
  {
    id: 3,
    qtd: 3,
    nome: "Dipirona 1g",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "Farmacorp",
    dataValidade: "2026-05-15",
    preco: 9.9,
    existe: true,
  },
  {
    id: 4,
    qtd: 5,
    nome: "Vitamina C 500mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "NutriLife",
    dataValidade: "2027-03-10",
    preco: 25.0,
    existe: true,
  },
  {
    id: 5,
    qtd: 5,
    nome: "Amoxicilina 500mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "BioSaúde",
    dataValidade: "2025-09-20",
    preco: 32.0,
    existe: true,
  },
  {
    id: 6,
    qtd: 10,
    nome: "Omeprazol 20mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "PharmaPlus",
    dataValidade: "2026-11-11",
    preco: 15.0,
    existe: true,
  },
  {
    id: 7,
    qtd: 2,
    nome: "Ácido Fólico 5mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "NutriPharma",
    dataValidade: "2027-01-01",
    preco: 10.0,
    existe: true,
  },
  {
    id: 8,
    qtd: 3,
    nome: "Cloroquina 250mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "MedCorp",
    dataValidade: "2025-08-01",
    preco: 40.0,
    existe: true,
  },
  {
    id: 9,
    qtd: 30,
    nome: "Losartana 50mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "CardioLife",
    dataValidade: "2026-02-01",
    preco: 22.0,
    existe: true,
  },
  {
    id: 10,
    qtd: 3,
    nome: "Metformina 850mg",
    linkImagem: "https://via.placeholder.com/150",
    fabricante: "DiabCare",
    dataValidade: "2026-07-01",
    preco: 28.0,
    existe: true,
  },
];

export default produtos;
